Run on EAPS by default.

diff --git a/test-all/run b/test-all/run
--- a/test-all/run
+++ b/test-all/run
@@ -6,19 +6,36 @@
 #
 #---------------------------------------------------------------------------------------------------
 
-# show my running environment
-echo ""; echo " ## Environment"
-env
+# show the arguments
+echo ""; echo " ## Arguments"
+echo $@
+
+
+# make sure the PATH is properly set
+export PATH="/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
 
 # show the directory
 echo ""; echo " ## Directory"
 pwd
 echo ""
-ls
+ls -lhrt
 
-# show the arguments
-echo ""; echo " ## Arguments"
-echo $@
+
+# show cvmfs
+echo ""; echo " ## List root (/)"
+ls -l /
+echo ""; echo " ## Load CMS default setup"
+ls -lhrt /cvmfs/cms.cern.ch/cmsset_default.sh
+source   /cvmfs/cms.cern.ch/cmsset_default.sh
+
+# show singularity
+echo ""; echo " ## Singularity"
+which singularity
+if [ ".$?" == "0" ]
+then
+  singularity --version
+else
+  echo " singularity not found"
 
 # now let's do what we came for
 echo ""; echo " ## Flags: cat /proc/cpuinfo | grep flags | sort -u"
@@ -26,6 +43,10 @@ flags=`cat /proc/cpuinfo | grep flags | sort -u`
 host=`hostname`
 echo " $host: $flags"
 
+# show my running environment
+echo ""; echo " ## Environment"
+env
+
 # now sleep to make those queue busy
-echo " $host: $flags"
-sleep 60
+echo ""; echo " ## Sleep 20"
+sleep 20
